name: NPM OIDC Authentication

on:
  push:
    branches: [main]

permissions:
  contents: read
  id-token: write   # REQUIRED for OIDC authentication

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Get ID Token from GitHub
        run: |
          ID_TOKEN=$(curl -sLS -H "User-Agent: actions/oidc-client" -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
          "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=sigstore" | jq .value | tr -d '"')
          echo "ID_TOKEN=${ID_TOKEN}" >> $GITHUB_ENV
          echo "✅ GitHub OIDC Token received."

      - name: Exchange ID Token for JFrog Access Token
        env:
            ID_TOKEN: ${{ env.ID_TOKEN }}
            JFROG_PLATFORM_URL: https://artifactory.stage.0658b-techopscore.com
        run: |
            echo "🔹 Fetching JFrog Access Token..."
            
            RESPONSE=$(curl -XPOST -H "Content-Type: application/json" \
              "${JFROG_PLATFORM_URL}/access/api/v1/oidc/token" \
              -d "{\"grant_type\": \"urn:ietf:params:oauth:grant-type:token-exchange\", \"subject_token_type\":\"urn:ietf:params:oauth:token-type:id_token\", \"subject_token\": \"${ID_TOKEN}\", \"provider_name\": \"github-oidc\"}")

            echo "🔹 Raw JFrog API Response: ${RESPONSE}"

            ACCESS_TOKEN=$(echo "$RESPONSE" | jq -r '.access_token')
            echo "🔹 Access Token Length = ${#ACCESS_TOKEN}"

            if [[ -z "$ACCESS_TOKEN" || "$ACCESS_TOKEN" == "null" ]]; then
              echo "❌ ERROR: Failed to get JFrog Access Token"
              exit 1
            fi

            echo "ACCESS_TOKEN=${ACCESS_TOKEN}" >> $GITHUB_ENV
            echo "✅ JFrog Access Token Stored."

      - name: Debug JFrog Authentication
        run: |
          curl -H "Authorization: Bearer $ACCESS_TOKEN" "https://artifactory.stage.0658b-techopscore.com/artifactory/api/system/ping"

      - name: Configure NPM Authentication
        run: |
          echo "registry=https://artifactory.stage.0658b-techopscore.com/artifactory/api/npm/npm-opensource/" > ~/.npmrc
          echo "@my-scope:registry=https://artifactory.stage.0658b-techopscore.com/artifactory/api/npm/npm-appcode-dev/" >> ~/.npmrc
          echo "//artifactory.stage.0658b-techopscore.com/artifactory/api/npm/npm-appcode-dev/:_authToken=${ACCESS_TOKEN}" >> ~/.npmrc

      - name: Install Dependencies
        run: npm install

      - name: Publish to JFrog Artifactory
        run: npm publish --access public
